require "spec/rake/spectask"

task :default => :integration

desc "Run unit specs"
Spec::Rake::SpecTask.new("integration") do |t|
  t.spec_opts = ['--format', 'specdoc', '--colour']
  # TODO: Remove the exclude once the framework issues that cause those specs
  # to hang get resolved.
  t.spec_files = FileList["#{File.dirname(__FILE__)}/**/*_spec.rb"].exclude('agent_interaction_spec.rb')
end

# This is all to make it so we can use natter from the source directory instead
# of installing it.
NATTER_DIR = File.expand_path(File.dirname(__FILE__) + '/../natter')
NATTER_PRIV_LIB = File.join(NATTER_DIR, 'priv', 'lib')
NATTER_SO_DEST = File.join(NATTER_PRIV_LIB, 'natter_expat.so')
NATTER_SO_SRC = File.join(NATTER_DIR, 'src', '.libs', 'natter_expat.so')

directory NATTER_PRIV_LIB

file NATTER_SO_DEST => NATTER_SO_SRC do |t|
  cp NATTER_SO_SRC, NATTER_SO_DEST
end

task :prepare => [NATTER_PRIV_LIB, NATTER_SO_DEST]
task :integration => :prepare
